### ISSUE TITLE
doesn't work for Trevor 

### ISSUE THREAD

**Issue by mbusenitz-blurb** [mbusenitz-blurb/xmlout#1]

**Comment by tehle** [comment]
MAC0412:Downloads tehle$ xmlout A\ Life\ Well\ Lived.Memoirs\ of\ Jack\ Northrup.blurb 

/usr/local/lib/node_modules/xmlout/xmlout.js:16
.action( (input) => {
                  ^
SyntaxError: Unexpected token >
    at Module._compile (module.js:439:25)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Function.Module.runMain (module.js:497:10)
    at startup (node.js:119:16)
    at node.js:902:3
